name: Android APK (Release)
on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install JS deps
        run: |
          cd ..
          yarn install --frozen-lockfile

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
